### ISSUE TITLE
Move this package to JuliaArrays

### ISSUE THREAD

**Issue by tkelman** [JuliaArrays/ArrayViews.jl#46]
cc @timholy this is mostly deprecated by now, but makes more sense in that org now I think.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/IndexingBenchmarks.jl too probably (or that should just go to JuliaArchive since it didn't really go anywhere?)

**Comment by timholy** [comment]
I moved ArrayViews. I'll let the authors of IndexingBenchmarks (@ViralBShah, @JaredCrean2 , @mschauer, @jiahao) decide what to do about that package. Closing this since the rest is not relevant to ArrayViews.
