### ISSUE TITLE
Maybe Retag?

### ISSUE THREAD

**Issue by ppalmes** [JuliaArrays/ArrayViews.jl#65]
(v1.0) pkg> add ArrayViews
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ArrayViews [a5c3d3bf]:
 ArrayViews [a5c3d3bf] log:
 ├─possible versions are: [0.1.0-0.1.1, 0.2.0-0.2.5, 0.3.0, 0.4.0-0.4.12, 0.5.0, 0.6.0-0.6.4, 0.7.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0-0.1.1, 0.2.0-0.2.5, 0.3.0, 0.4.0-0.4.12, 0.5.0, 0.6.0-0.6.4, 0.7.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

However, if I use: add ArrayViews#696a741
it works

Julia v0.7 seems to be fine with no errors/warnings

**Comment by andreasnoack** [comment]
See https://github.com/JuliaArrays/ArrayViews.jl/issues/64
